    // ════════════════════════════
    // CONFIG & STATE (ONCOLOGY)
    // ════════════════════════════
    
    const CANCER_TYPES = {
      lung: { name: '🫁 Lung', color: '#0ea5e9', bg: '#f0f9ff' },
      breast: { name: '🎀 Breast', color: '#ec4899', bg: '#fdf2f8' },
      gi: { name: 'GI', color: '#eab308', bg: '#fefce8' },
      gu: { name: 'GU', color: '#3b82f6', bg: '#eff6ff' },
      haem: { name: '💧 Haem', color: '#8b5cf6', bg: '#f5f3ff' },
      cns: { name: '🧠 CNS', color: '#c026d3', bg: '#fdf4ff' },
      gynae: { name: '🌸 Gynae', color: '#d946ef', bg: '#fdf4ff' },
      hn: { name: 'H&N', color: '#10b981', bg: '#ecfdf5' },
      skin: { name: '☀️ Skin', color: '#f59e0b', bg: '#fffbeb' },
      reg: { name: '📋 Reg', color: '#dc2626', bg: '#fef2f2' },
      guide: { name: '📖 Guide', color: '#0d9488', bg: '#ccfbf1' }
    };

    const SOURCE_TYPES = {
      'intl-study': { name: 'Nghiên cứu Quốc tế', color: '#6366f1', bg: '#e0e7ff' },
      'intl-guideline': { name: 'Guideline Quốc tế', color: '#0d9488', bg: '#ccfbf1' },
      'vn-moh': { name: 'Bộ Y tế Việt Nam', color: '#dc2626', bg: '#fee2e2' },
      'vn-association': { name: 'Hội chuyên khoa VN', color: '#16a34a', bg: '#dcfce7' },
      'fda': { name: 'FDA / EMA', color: '#7c3aed', bg: '#faf5ff' }
    };

    const DESIGNS = {
      'rct': { name: 'Thử nghiệm lâm sàng (RCT)' },
      'phase1': { name: 'Lâm sàng Giai đoạn I' },
      'phase2': { name: 'Lâm sàng Giai đoạn II' },
      'phase3': { name: 'Lâm sàng Giai đoạn III' },
      'meta': { name: 'Tổng quan / Meta-Analysis' },
      'cohort': { name: 'Nghiên cứu quan sát / Thuần tập' },
      'guideline': { name: 'Hướng dẫn / Khuyến cáo' },
      'review': { name: 'Bài tổng quan y khoa' },
      'other': { name: 'Khác' }
    };

    const IMPACTS = {
      'practice-changing': { name: 'Practice-Changing', color: '#dc2626', bg: '#fef2f2' },
      'regulatory': { name: 'Regulatory', color: '#7c3aed', bg: '#faf5ff' },
      'informative': { name: 'Informative', color: '#2563eb', bg: '#eff6ff' },
      'early-signal': { name: 'Early Signal', color: '#d97706', bg: '#fffbeb' },
      'negative': { name: 'Negative', color: '#4b5563', bg: '#f3f4f6' }
    };

    const SAMPLE_STUDIES = [
      {
        id: "study_onco_beamion_lung_2026",
        title: "Beamion LUNG-1: Zongertinib cho ung thư phổi không tế bào nhỏ (NSCLC) đột biến HER2",
        drug: "Zongertinib",
        sourceType: "intl-study",
        cancerType: "lung",
        design: "phase1",
        presentedAt: "ELCC 2026",
        intervention: "Zongertinib 120 mg PO QD (<90kg) hoặc 180 mg (>=90kg)",
        primaryEndpoint: "Tỷ lệ đáp ứng khách quan (ORR) (BICR) — 76%",
        medianPFS: "14.4 tháng",
        medianOS: "Chưa đạt",
        keyResults: "ORR: 76%, PFS: 14.4 tháng. Zongertinib cho thấy hiệu quả duy trì ở bệnh nhân NSCLC tiến triển có đột biến HER2 chưa điều trị trước đó.",
        impact: "informative",
        year: 2026,
        organization: "NEJM",
        phase: "Phase I",
        sampleSize: null,
        population: "NSCLC không vảy tiến triển/di căn có đột biến kích hoạt HER2 TKD; chưa điều trị; ECOG PS 0-1; 30% di căn não",
        summary: "Zongertinib cho thấy hiệu quả bền vững ở bệnh nhân ung thư phổi không tế bào nhỏ có đột biến HER2 tiến triển, chưa điều trị. Các biến cố bất lợi liên quan đến điều trị chủ yếu ở mức độ nhẹ.",
        detailedConclusion: "Zongertinib cho thấy hiệu quả bền vững ở bệnh nhân ung thư phổi không tế bào nhỏ có đột biến HER2 tiến triển, chưa điều trị. Các biến cố bất lợi liên quan đến điều trị chủ yếu ở mức độ nhẹ.",
        fdaStatus: "Đã phê duyệt (Accelerated approval) Feb 2026",
        sourceUrl: "https://www.nejm.org/doi/full/10.1056/NEJMoa2516969",
        file: "",
        subgroups: {},
        icd10: ["C34", "C34.9"],
        asianData: false,
        bookmarked: true,
        createdAt: new Date().toISOString()
      },
      {
        id: "study_onco_car_prism_2026",
        title: "CAR-PRISM: Ciltacabtagene autoleucel (Cilta-cel) cho Đa u tủy (Smoldering MM)",
        drug: "Ciltacabtagene autoleucel",
        sourceType: "intl-study",
        cancerType: "haem",
        design: "phase2",
        presentedAt: "AACR 2026",
        intervention: "Cilta-cel truyền tĩnh mạch 1 lần sau điều trị giảm bạch cầu; không dùng phác đồ cảm ứng",
        primaryEndpoint: "Tỷ lệ âm tính MRD — 100%",
        medianPFS: "Chưa đạt",
        medianOS: "Chưa đạt",
        keyResults: "MRD âm tính 100%. Không có tiến triển thành bệnh thể hoạt động ở thời gian theo dõi trung vị 15.3 tháng.",
        impact: "early-signal",
        year: 2026,
        organization: "AACR",
        phase: "Phase II",
        sampleSize: null,
        population: "Đa u tủy tiến triển âm ỉ nguy cơ cao theo mô hình 20/2/20; ECOG PS 0-1; tuổi trung vị 58",
        summary: "Cilta-cel điều trị bước 1 tạo ra đáp ứng sâu và bền vững ở bệnh nhân đa u tủy tiến triển âm ỉ (smoldering) nguy cơ cao.",
        detailedConclusion: "Cilta-cel (Carvykti) điều trị bước 1 tạo ra đáp ứng sâu và bền vững ở đa u tủy tiến triển âm ỉ nguy cơ cao, với 100% âm tính MRD và không bệnh nhân nào tiến triển thành bệnh thể hoạt động tại thời điểm trung vị 15.3 tháng.",
        fdaStatus: "Carvykti đã được duyệt cho RRMM 2024",
        sourceUrl: "",
        file: "",
        subgroups: {},
        icd10: ["C90", "C90.0"],
        asianData: false,
        bookmarked: true,
        createdAt: new Date().toISOString()
      },
      {
        id: "study_onco_ideatelung01_2025",
        title: "IDeate-Lung01: Ifinatamab deruxtecan (I-DXd) trong SCLC",
        drug: "Ifinatamab deruxtecan",
        sourceType: "intl-study",
        cancerType: "lung",
        design: "phase2",
        presentedAt: "WCLC 2025",
        intervention: "I-DXd 12 mg/kg IV Q3W",
        primaryEndpoint: "ORR (BICR) — 48.2%",
        medianPFS: "4.9 tháng",
        medianOS: "10.3 tháng",
        keyResults: "ORR 48.2%; mPFS 4.9 tháng; mOS 10.3 tháng ở bệnh nhân ES-SCLC đã qua điều trị.",
        impact: "informative",
        year: 2025,
        organization: "FDA",
        phase: "Phase II",
        sampleSize: null,
        population: "Bệnh nhân ES-SCLC tiến triển sau hóa trị nền platinum; >=1 bước điều trị trước đó",
        summary: "Ifinatamab deruxtecan hứa hẹn trở thành thuốc ADC đích B7-H3 đầu tiên cho SCLC lan tỏa đã qua điều trị.",
        detailedConclusion: "Nếu được phê duyệt, I-DXd sẽ là ADC hướng B7-H3 đầu tiên được chỉ định cho ung thư phổi tế bào nhỏ giai đoạn lan tỏa đã qua điều trị.",
        fdaStatus: "Chờ duyệt — Priority Review cấp Tháng 4 2026; PDUFA Tháng 10 2026",
        sourceUrl: "",
        file: "",
        subgroups: {},
        icd10: ["C34", "C34.9"],
        asianData: false,
        bookmarked: false,
        createdAt: new Date().toISOString()
      },
      {
        id: "study_onco_optimum02_2026",
        title: "OptimUM-02: Darovasertib + crizotinib cho U hắc tố màng bồ đào",
        drug: "Darovasertib + crizotinib",
        sourceType: "intl-study",
        cancerType: "skin",
        design: "phase3",
        presentedAt: "Sắp trình bày",
        intervention: "Darovasertib + crizotinib",
        primaryEndpoint: "PFS (BICR) — 37.1% vs 5.8%",
        medianPFS: "6.9 tháng",
        medianOS: "Chưa đạt",
        keyResults: "mPFS cải thiện từ 3.1 tháng lên 6.9 tháng.",
        impact: "informative",
        year: 2026,
        organization: "OncLive",
        phase: "Phase II/III",
        sampleSize: null,
        population: "U hắc tố màng bồ đào di căn âm tính với HLA-A*02:01, bước 1",
        summary: "Nghiên cứu ngẫu nhiên đầu tiên chứng minh lợi ích sống còn bệnh không tiến triển ở bệnh nhân u hắc tố màng bồ đào di căn bước 1.",
        detailedConclusion: "OptimUM-02 là nghiên cứu ngẫu nhiên đầu tiên chứng minh lợi ích lâm sàng và thống kê có ý nghĩa về PFS trong điều trị bước 1 u hắc tố màng bồ đào di căn âm tính HLA-A*02:01.",
        fdaStatus: "Dự kiến nộp NDA cuối 2026",
        sourceUrl: "",
        file: "",
        subgroups: {},
        icd10: ["C69", "C69.3"],
        asianData: false,
        bookmarked: false,
        createdAt: new Date().toISOString()
      },
      {
        id: "study_onco_breakwater_2024",
        title: "BREAKWATER: Encorafenib + cetuximab + mFOLFOX6 trong ung thư đại trực tràng",
        drug: "Encorafenib + cetuximab + mFOLFOX6",
        sourceType: "intl-study",
        cancerType: "gi",
        design: "phase3",
        presentedAt: "ESMO 2024",
        intervention: "Encorafenib 300 mg PO QD + cetuximab 500 mg/m2 + mFOLFOX6 Q2W",
        primaryEndpoint: "PFS (BICR) — 67% vs 24%",
        medianPFS: "11.3 tháng",
        medianOS: "Chưa đạt",
        keyResults: "Cải thiện đáng kể PFS ở bước 1.",
        impact: "practice-changing",
        year: 2024,
        organization: "FDA",
        phase: "Phase III",
        sampleSize: null,
        population: "Ung thư đại trực tràng di căn có đột biến BRAF V600E chưa điều trị; RAS wild-type",
        summary: "Phác đồ phối hợp trở thành tiêu chuẩn chăm sóc bước 1 mới cho ung thư đại trực tràng di căn đột biến BRAF V600E.",
        detailedConclusion: "Encorafenib kết hợp cetuximab và mFOLFOX6 là một lựa chọn tiêu chuẩn chăm sóc bước 1 mới cho bệnh nhân ung thư đại trực tràng di căn có đột biến BRAF V600E.",
        fdaStatus: "Đã phê duyệt (Traditional approval) Feb 24, 2026",
        sourceUrl: "",
        file: "",
        subgroups: {},
        icd10: ["C18", "C20"],
        asianData: false,
        bookmarked: true,
        createdAt: new Date().toISOString()
      }
    ];

    if (typeof module !== 'undefined' && module.exports) {
      module.exports = { CANCER_TYPES, SOURCE_TYPES, DESIGNS, IMPACTS, SAMPLE_STUDIES };
    }
